### ISSUE TITLE
Incorrect parsing of line with only key

### ISSUE THREAD

**Issue by bpradeep20** [etingof/apacheconfig#33]
For config file:

```
<main>
   key1
   key2 value2
</main>

```

This is raising following error

> raise ApacheConfigError("Illegal character '%s'" % t.value[0])
> apacheconfig.error.ApacheConfigError: Illegal character 'k'

while perl parse will parse into

```
{  
   "main" => {  
      "key1"=> undef,
      "key2"=> "value2"
   }
}
```
Can you please check?

**Comment by zhaiyifei** [comment]
I also encountered this problem.
I find that this is the problem of regular matching.
Modify this function in lexer.py
`def  t_OPTION_AND_VALUE(self, t): 

        r'[^ \n\r\t=#]+[ \t=]*[^\r\n#]+'  # new pattern
        # r'[^ \n\r\t=#]+[ \t=]+[^\r\n#]+'  # old pattern
        if t.value.endswith('\\'):
            t.lexer.code_start = t.lexer.lexpos - len(t.value)
            t.lexer.begin('multiline')
            return

        lineno = len(re.findall(r'\r\n|\n|\r', t.value))
        # Add the following two lines.
        if not re.match(r'[^ \n\r\t=#]+[ \t=]+[^\r\n#]+', t.value):
            t.value += " = "
        option, value = self._parse_option_value(t.value)
        process, option, value = self._pre_parse_value(option, value)
        if not process:
            return
        if value.startswith('<<'):
            t.lexer.heredoc_anchor = value[2:].strip()
            t.lexer.heredoc_option = option
            t.lexer.code_start = t.lexer.lexpos
            t.lexer.begin('heredoc')
            return
        t.value = option, value
        t.lexer.lineno += lineno
        return t`
Hope for early repair

**Comment by zhaiyifei** [comment]
> Hi,
> 
> Did you got time to look into it?

Hi, 
What can I do for you?
When I have time。

**Comment by sydneyli** [comment]
Yes, I can try to fix this! I think we have to.

**Comment by ssumit3** [comment]
Hi,
This problem still exits. However now the exception obtained is different. Attaching the config and exception obtained:
```
<main>
key1  val1
key2
</main>

```
Exception obtained:
```
Traceback (most recent call last):
  File "/myproject/main.py", line 93, in <module>
    a = create_object_from_config(config_name)
  File "/myproject/main.py", line 76, in create_object_from_config
    config_dict = load_config(config_name)
  File "/myproject/loader.py", line 40, in load_config
    config_dictionary = config_loader.loads(config)
  File "/myproject/apacheconfig/loader.py", line 343, in loads
    self._ast_cache[source] = self._walkast(ast)
  File "/myproject/apacheconfig/loader.py", line 319, in _walkast
    return handler(ast[1:])
  File "/myproject/apacheconfig/loader.py", line 44, in g_config
    items = self._walkast(subtree)
  File "/myproject/apacheconfig/loader.py", line 319, in _walkast
    return handler(ast[1:])
  File "/myproject/apacheconfig/loader.py", line 95, in g_contents
    items = self._walkast(subtree)
  File "/myproject/apacheconfig/loader.py", line 319, in _walkast
    return handler(ast[1:])
  File "/myproject/apacheconfig/loader.py", line 83, in g_block
    items = self._walkast(subtree)
  File "/myproject/apacheconfig/loader.py", line 319, in _walkast
    return handler(ast[1:])
  File "/myproject/apacheconfig/loader.py", line 95, in g_contents
    items = self._walkast(subtree)
  File "/myproject/apacheconfig/loader.py", line 319, in _walkast
    return handler(ast[1:])
  File "/myproject/apacheconfig/loader.py", line 145, in g_statement
    option, value = ast[:2]
ValueError: need more than 1 value to unpack

```

Changing the first line in method g_statement(self, ast) in loader.py as below is fixing this issue for me but i am not sure of the fix:

```
# option, value = ast[:2]
option = ast[0]
if not len(ast) > 1:
        return {
                option: None
        }
value = ast[1]

```

**Comment by sydneyli** [comment]
@ssumit3 Yes, you're correct! Thanks for catching that-- we built in support in the lexer and parser, but forgot to do it at the loader-level.
