### ISSUE TITLE
Getting syntax error on trying to use the Parser.

### ISSUE THREAD

**Issue by ssumit3** [etingof/apacheconfig#69]
Hi, 

On trying to parse a config file using the parser, I get the following syntax error:

ERROR:/my_project/apacheconfig/lexer.py:358: Invalid regular expression for rule 't_OPTION_AND_VALUE'. unbalanced parenthesis
ERROR:/my_project/apacheconfig/lexer.py:358. Make sure '#' in rule 't_OPTION_AND_VALUE' is escaped with '\#'
Traceback (most recent call last):
  File "/my_project/test.py", line 114, in <module>
    create_object_from_config()
  File "/my_project/test.py", line 75, in create_object_from_config
    dict = load_config(config_path)
  File "/my_project/test.py", line 39, in load_config
    with make_loader(**options) as config_loader:
  File "/opt/python/python-2.7/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/my_project/apacheconfig/__init__.py", line 24, in make_loader
    yield ApacheConfigLoader(ApacheConfigParser(ApacheConfigLexer()),
  File "/my_project/apacheconfig/lexer.py", line 144, in __init__
    self.reset()
  File "/my_project/apacheconfig/lexer.py", line 152, in reset
    errorlog=log if self._debug else None
  File "/usr/local/python/python-2.7/std/lib/python2.7/site-packages/ply/lex.py", line 910, in lex
    raise SyntaxError("Can't build lexer")
SyntaxError: Can't build lexer

I am using the following options:

options = {
        'noescape': True,
        'autotrue': True,
        'ccomments': False
    }

**Comment by etingof** [comment]
Let's summon @sydneyli  ;-)

**Comment by sydneyli** [comment]
Oh no! @ssumit3, can get us the commit you're on and your version of ply-- run `git rev-parse HEAD` and also `pip freeze | grep ply` and tell us the results?

**Comment by etingof** [comment]
GitHub assumes that this issue is resolved by #71. @ssumit3 - feel free to reopen it if needed.

**Comment by ssumit3** [comment]
This got resolved. Thanks.
